name: Issue Inactive Checker

on:
  schedule:
    - cron: "0 13 * * *" # Every Monday at 1PM UTC (9AM EST)

permissions:
  contents: read

jobs:
  issue-close-require:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Cannot Replicate
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
          labels: "Resolution: Cannot Replicate"
          inactive-day: 20
      - name: Needs Reproducer
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
          labels: "Status: Needs Reproducer"
          inactive-day: 20
